liste_caracteres_bloques = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "b", "c", "d", "f", "i", "j", "s", "t", "u", "v"]
liste_caracteres_fleche = ["w", "x", "y", "z"]
liste_caracteres_maison = []
coordonnees_interieur_maison = []
coordonnees_porte_maison = []
maison_shop = False
maison_grotte = False
niveau_monstres = 1
fond_ecran_combat = "imagesCombat/fondEcranCombat.png"
