liste_caracteres_bloques = ["i", "j", "k", "n", "q", "s", "t", "u", "7", "v"]
liste_caracteres_fleche = ["w", "x", "y", "z"]
liste_caracteres_maison = []
coordonnees_interieur_maison = []
coordonnees_porte_maison = []
maison_shop = False
maison_grotte = False
niveau_monstres = 1
fond_ecran_combat = "imagesCombat/fondEcranCombat.png"
